local game_str = {
    -- UI 文本
    -- 回到角色選擇畫面
    back_to_select = "回到角色選擇畫面",
    you_cannot_use_this_item_while_the_game_is_paused = "你無法在遊戲暫停時使用該道具。",
    the_gift_CN = "恩賜之物",
    teleportation = "傳送",
    Currency_exchange = "通貨交換",
    death_text = {
        "在記錄點重生", "在藏身處復活", "在城鎮重生", "在開始地圖頭目遭遇之後復活，會移除區域 內所有其他遭遇和怪物"
    },
    relife_text = {"在記錄點重生","在藏身處復活","在城鎮重生"},
    confirm = "確定",
    Unable_to_deserialise = "> 已斷線: Unable to deserialise packet with pid",
    Wish_list = "願望清單",
    login_fail_text_list = {"與副本連線失敗。","伺服器斷線。","> Steam：未連接到 Steam","Steam：未連接到 Steam","已斷線","操作逾時","由於在短時間內執行過多指令，因此被伺服器暫時切斷連線。"},
    IP_blocked_CH = "此 IP 已被封鎖。有任何疑問請與客服中心聯繫。",
    Server_maintenance = "伺服器關閉維修中，請稍後再試。",
    Account_banned = "Your account has been banned by an administrator.",
    Login_error = "登入錯誤",
    Official_login_error = {"此帳號已被鎖定，請至信箱確認解鎖郵件中的解鎖碼並在此輸入。","重新寄送解鎖信"},
    Account_Other_used = "此帳號已被其他使用者登入。",
    first_log_text_list = {"Login Error","The operation timed out.","Entry to this league has closed.","Abnormal Disconnection","Disconnection","Disconnected","偵測到老舊的 GPU 驅動程式。請更新至最新版本。","你的帳號沒有《流亡黯道 2》的搶 先體驗資格。立即在我們的網站上領取搶先體驗金鑰或購買資格。","搶先體驗"},
    IP_blocked_EN = "Your IP has been banned. Please contact support if you think this is a mistake.",
    I_Have = "我擁有的",
    I_Need = "我需要的",
    agree = "同意",
    continue = "繼續",
    Create_Account = "建立帳號",
    To_use_Steam_To_log_in = "若要使用 Steam 登入，你必須先建立一個 Steam 的《流亡黯道》帳號。",
    Account_name = "帳號名稱",
    log_in = "登入",
    Verified = "已驗證。",
    Start_the_game = "開始遊戲",
    Log_in_town_or_hideout = "登入至城鎮或藏身處",
    Establish_roles = "建立角色",
    clear = "/clear",
    invite = "/invite ",
    kick = "/kick ",
    town = "town",
    Abyss = "Abyss_",
    temple = "神殿",
    backpack = "背包",
    Continue_Game = "繼續遊戲",
    Leave_the_game = "離開遊戲",
    Task_prop_text = {"知識之書","知識之結晶核心"},
    Demon_dispelling_items = "祛魔物品",
    Goodbye = "再會",
    The_recast_platform = "重鑄台",
    Destroy_three_similar_items_and_recast_them_into_a_new_one = "摧毀三個相似的物品，重鑄為一個新的物品",
    Reset_talent_points = "重置天賦點數",
    Purchase_or_sell = "購買或販賣",
    Self_CH = "个人",
    Warehouse_text = "个仓",
    Warehouse = "倉庫",
    Emphasize_the_item = "強調物品",
    Guild_CH = "公会",
    Guild_TWCH = "公會",
    Guild_Warehouse = "公會倉庫",
    Guild_Warehouse_text = "公仓",
    Dripping_in = "滴注中",
    Dripping = "滴注",
    Delirium = "譫妄",
    Map_Key_Class_1 = "地圖鑰匙（階級 1）",
    Map_Key_Class_15 = "地圖鑰匙（階級 15）",
    Map_Key_Class_16 = "地圖鑰匙（階級 16）",
    Recycling_equipment = "回收具有品質或插槽的裝備，以獲得品質通貨和工匠碎片",
    Restructuring = "重組",
    World_map = "世界地圖",
    Fantom_Fragment = "幻像斷片",
    Received_team_invitation = "已收到隊伍邀請",
    Refuse = "拒絕",
    Check_point = "記錄點",
    Missions_text = {"接受任務" ,"繼續"},
    You_can_t_throw_this_item = "你無法將此道具丟置於此。請問要摧毀它嗎？",
    Reserved = "保留",
    Gold = {"黃金", "金幣"},
    The_Book_of_Knowledge = "知識之書",
    The_crystallization_core_of_knowledge_CH = "知識之結晶核心",
    The_Knowledge_Scroll = "知識卷軸",
    Return_the_Map_Talent = "返還輿圖天賦",
    Accept = "接受",
    Remaining = "剩餘",
    Refine = "液態",
    The_delirium_of_players = "區域中玩家的[Delirious|譫妄]為{0}%",
    Private_message = "私訊",
    Map_Key_CH = "地圖鑰匙",
    Transfer_point_CH = "傳送點",
    The_Gate_of_the_Outland_CH = "異界之門",
    Decayed_backpack_charging_CH = "腐爛背包充能",
    Are_you_sure_you_want_to_leave_CH = "你確定要離開此區域嗎？",
    Yes_CH = "是",
    Switch_CH = "開關",
    Door_CH = "門",
    Handle_CH = "把手",
    Hide_props_CH = "隱藏道具",
    Map_Device_CH = "地圖裝置",
    within_the_scope_CH = "範圍內",
    Buy_or_Sell_items_CH = "購買或販賣物品",
    Temporary_prop_CN = "暫緩道具",
    Confirm_TWCH = "確認",
    Waiting_for_the_player_to_accept_TWCH = "等待玩家接受交易請求...",
    Gemstone_cutting_TWCH = "寶石切割",
    Skill_CH = "技能",
    Selected_TWCH = "精選",
    Social_TWCH =  "社交",
    Role_TWCH = "角色",
    Activity_TWCH = "活動",
    Options_TWCH = "選項",
    Gifted_skills_TWCH = "天賦技能",
    Dark_Coin_TWCH = "黯幣",
    Startup_failed_TWCH = "啟動失敗。地圖無法進入。",
    Task_Reward_TWCH = "任務獎勵",
    Please_choose_a_reward_TWCH = "請選擇一個獎勵",
    Choose_Hideout_TWCH = "選擇藏身處",
    Holy_Land_Lock_Cabinet_TWCH = "聖域鎖櫃",
    Error_Unable_to_enter_TWCH = "錯誤：無法進入。",
    Server_disconnected_TWCH = "錯誤：無法進入，原因：伺服器斷線。",
    Corruption_Sanctuary_TWCH = "腐化聖域",
    Region_TWCH = "地區",
    Power_TWCH = "勢力",
    Crossing_TWCH = "穿越",
    MapLeaguePortal_TWCH = "界域之門",
    Map_completed_TWCH = "地圖完成",
    There_are_0_remaining_monsters_TWCH = "剩餘 0 隻怪物",
    Return_to_the_surface_TWCH = "重返地表",
    Monument_plaque_TWCH = "碑牌",
    Already_owned_TWCH = "已擁有",
    ALL_text_TWCH = "全部",
    Completed_orders_TWCH = "完成的訂單",
    Order_cancellation_TWCH = "訂單取消",
    Close_Order_TWCH = "關閉訂單",
    Listed_orders_TWCH = "列出的訂單",
    What_I_need_TWCH = "我需要的",
    The_transaction_ratio_you_have_chosen_TWCH  = "你選擇的交易比率低於當下市集需求的標準。",
    The_transaction_ratio_you_have_chosen_CHANGE_TWCH  = "你選擇的交易比率低於當下市集需求的標準。",
    Cancel_TWCH = "取消",
    Place_an_order_TWCH = "下訂單",
    MapDevice_TWCH = "黃金製圖儀",
    Invitation_to_showcase_Skeleton_Mark_TWCH = "展示骷髏馬克的邀請",
    The_Holy_Temple_TWCH = "聖潔神殿",
    Click_to_start_the_ritual_TWCH = "點擊以開始祭祀",
    Monsters_are_imprisoned_by_powerful_essence_TWCH = "怪物受到強大的精髓禁錮。",
    Water_gate_control_rod_TWCH = "水閘門控制桿",
    The_Broken_Mirror_TWCH = "破碎之鏡",
    The_arena_TWCH = "競技場",
    Identify_the_item_TWCH = "鑑定物品",
    Sacrifice_TWCH = "獻祭",
    Worm_Tunnel_Destroyer_TWCH = "蠕蟲隧道破壞者",
    The_Stone_Array_Altar_TWCH = "石陣祭壇",
    Pioneer_Beacon_Tower_TWCH = "先行者烽塔",
    Treasure_binds_the_soul_TWCH = "寶藏束縛靈魂",
    Safe_deposit_box_TWCH = "保險箱",
    The_restraining_hand_of_the_cracked_king_TWCH = "裂痕君王的抑制之手",
    The_hand_of_inhibition_TWCH = "抑制之手",
    The_Seal_of_Runes_TWCH = "符文之印",
    Barbara_Soul_TWCH = "芭芭拉的精魂",
    The_Soul_of_Palasa_TWCH = "帕拉薩之魂",
    The_staircase_TWCH = "樓梯",
    The_Researcher_Safe_Box_TWCH = "研究者的保險箱",
    Rune_Stele_TWCH = "符文豐碑",
    Magical_Stone_Formation_TWCH = "魔幻石陣",
    You_cannot_re_enter_this_area_after_death_TWCH = "你在死亡後無法重新進入此區域。",
    The_Stone_Coffin_TWCH = "石棺",
    The_Altar_of_Signs_TWCH = "徵兆祭壇",
    Evening_Bell_TWCH = "晚鐘",
    Rune_Giant_Stone_TWCH = "符文巨石",
    Strengthening_Runes_TWCH = "強化符文",
    The_Chain_of_Time_and_Space_TWCH = "時空之鏈",
    The_turret_TWCH = "砲塔",
    Armor_Forge_Master_Safe_Box_TWCH = "護甲鍛造師的保險箱",
    Are_you_sure_you_want_to_teleport_to_this_player_location_TWCH = "你確定要傳送至此玩家的位置？",
    Waypoint = "Waypoint",
    Copy_Canager_CH = "副本管理員",
    New_Dungeon_CH = "新副本",
    Black_Cathedral = "黑色大教堂",
    Hidden_Creature = "潛伏的生物",
    Enter_CH = "進入",
    The_Invitation_of_Skeleton_Mark_TWCH = "骷髏馬克的邀請",
    The_Container_of_Mark_the_Skeleton_TWCH = "骷髏馬克的容器",
    Skull_Mark_TWCH = "骷髏馬克",
    Obtain_the_ring_TWCH = "取得戒指",
    Enhancement_Item_List_TWCH = {"瓦爾寶珠","點金石"},
    Not_Identified_TWCH = "未鑑定",
    Contaminated_TWCH = "已汙染",
    Steam_Copy_Login_Request_TWCH = "Steam：複製的登入請求",
    Violate_The_Rules = "此帳號因違反下述狀況，已經被遊戲管理者停權了。",
    Return_To_The_Login_Screen_TWCH = "回到登入畫面",
    mini_target_ = {"AbyssCrackActive","AbyssPitActive","RuneMarkersActive"},
    This_alliance_entrance_has_been_closed = "此聯盟入口已經關閉。",
    Friend_invitation = "好友邀請：",
    Friend = "好友",
    -- 暗金碑牌
    Great_Plan_TWCH = "偉大計劃",


    -- 通货
    Div_Orb_TWCH = "神聖石",
    Mirror_TWCH = "卡蘭德的魔鏡",
    Vaal_Orb_TWCH = "瓦爾寶珠",
    Exalted_Orb_TWCH = "崇高石",
    Orb_of_Transmutation_TWCH = "蛻變石",
    Orb_of_Augmentation_TWCH = "增幅石",
    Regal_Orb_TWCH = "富豪石",
    Orb_of_Alchemy_TWCH = "點金石",
    Greater_Orb_of_Transmutation_TWCH = "高階蛻變石",
    Greater_Orb_of_Augmentation_TWCH = "高階增幅石",

    -- NPC
    Break_NPC = "佐林",
    Break_NPC_Text = "佐林 的物品",
    Break_NPC1 = "札卡",
    Break_NPC1_Text = "札卡 的物品",
    Appraisal_NPC = "多里亞尼",
    Exchange_NPC1 = "艾瓦",
    Exchange_NPC2 = "安潔",
    Sale_NPC = "澤莉娜",


    --API 文本
    required_plaques = {"祭祀碑牌", "先行者碑牌", "譫妄碑牌", "裂痕碑牌", "總督的先行者碑牌", "探險碑牌"},


    --英文
    the_account_to_be_logged_in = "This operation requires the account to be logged in.",
    TowerAugmentation = "TowerAugmentation",
    Delirium_ = "Delirium_",
    Item_category = {"One Hand Mace","Two Hand Mace","Warstaff","Wand","Staff","Crossbow","Sceptre","Bow","Body Armour","Helmet","Gloves","Boots","Shield","Quiver","Focus","Amulet","Belt","Ring","Spear","Buckler"},
    QuestItem = "QuestItem",
    StackableCurrency = "StackableCurrency",
    StashPlayer_EN = "StashPlayer",
    StashGuild_EN = "StashGuild",
    MapDevice = "MapDevice",
    TreasureVaultHammerActive = "TreasureVaultHammerActive",
    Map_EN = "Map",
    MapUniqueWildwood = "MapUniqueWildwood", -- 翠绿荒林
    UncutSkillGem_EN = "UncutSkillGem",
    UncutReservationGem_EN = "UncutReservationGem",
    UncutSupportGem_EN = "UncutSupportGem",
    Buy_or_Sell_items_EN = "Buy or Sell items",
    Checkpoints_EN = "Checkpoints",
    Claimable_EN = "Claimable",
    Abyss_EN = "Abyss",
    Entrance_EN = "Entrance",
    Waypoint_EN = "Waypoint",
    Boss_EN = "Boss",
    RitualRuneFinished_EN = "RitualRuneFinished",
    Abyss_Boss_EN = "Abyss_Boss",
    MapUberBoss_IronCitadel_EN = "MapUberBoss_IronCitadel",  -- 钢铁城寨
    MapUniqueVault_EN = "MapUniqueVault",  -- 卡玛隆秘宝库
    MapBurialBgo_EN = "MapBurialBog",  -- 埋葬沼泽
    


    -- 小地图信息
    RitualRune_EN = "RitualRune",
    RareMonsterAlive_EN = "RareMonsterAlive",
    AfflictionInitiator_EN = "AfflictionInitiator",
    AbyssChestActive_EN = "AbyssChestActive",
    RuneMarkersActive_EN = "RuneMarkersActive",
    BossSummoningLocationActive_EN = "BossSummoningLocationActive",
    UniqueMonsterAlive_EN = "UniqueMonsterAlive",
    BossCheckpointActive_EN = "BossCheckpointActive",
    Checkpoint_EN = "Checkpoint",
    Essence_EN = "Essence",
    AbyssCrackActive_EN = "AbyssCrackActive",
    

    -- 控件文本(CT)
    exit_to_character_selection = "exit_to_character_selection",
    life_orb = "life_orb",
    mana_orb = "mana_orb",
    respawn_at_checkpoint_button = "respawn_at_checkpoint_button",
    loading_screen_tip_label = "loading_screen_tip_label",
    resume_game = "resume_game",
    username_textbox = "username_textbox",
    password_textbox = "password_textbox",
    login_button = "login_button",
    tab_list_button = "tab_list_button",
    ritual_open_shop_button_CT = "ritual_open_shop_button",
    bottom_icons_layout_CT = "bottom_icons_layout",
    quest_state_changed_button_CT = "quest_state_changed_button",


    -- 路径名
    Ritual_PATH = "Metadata/Terrain/Leagues/Ritual/RitualRuneInteractable",
    Monolith_PATH = "Metadata/MiscellaneousObjects/Monolith",
    AbyssSubAreaTransition_PATH = "Metadata/MiscellaneousObjects/Abyss/AbyssSubAreaTransition",
    ZigguratMapDevice_PATH = "Metadata/Terrain/Missions/Hideouts/Objects/MapDeviceVariants/ZigguratMapDevice",
    DeliriumInitiator_PATH = "Metadata/Terrain/Gallows/Leagues/Delirium/Objects/DeliriumInitiator",
    BreachObject_PATH = "Metadata/MiscellaneousObjects/Breach/BreachObject",
    AbyssCrack_PATH = "Metadata/MiscellaneousObjects/Abyss/AbyssCrack",
    DoodadDaemonShardPack_PATH = "Metadata/Monsters/LeagueDelirium/DoodadDaemons/DoodadDaemonShardPack",
    TormentedSpiritofthe_PATH = "Metadata/Monsters/TormentedSpirits/TormentedSpiritofthe",
    BasicStrongbox_PATH = "Metadata/Chests/StrongBoxes/BasicStrongbox",
    StrongBoxes_PATH = "Metadata/Chests/StrongBoxes",
    Abyss_PATH = "Metadata/Chests/Abyss/Abyss",
    RitualRuneLight_PATH = "Metadata/Terrain/Leagues/Ritual/RitualRuneLight",


    -- 技能
    DemonFormPlayer_ENSK = "DemonFormPlayer",


    --stateMachineList数据(SML)
    clicked_SML = "clicked",
    lever_pull_SML = "lever_pull",
    lever_pulled_SML = "lever_pulled",
    interacted_SML = "interacted",
    detonate_SML = "detonate",
    started_SML = "started",
    opened_SML = "opened",
    unlocked_SML = "unlocked",
    doomepk_SML = "doomepk",
    active_SML = "active",
    current_state_SML = "current_state",
    interaction_enabled_SML = "interaction_enabled",
    goodbye_SML = "goodbye",
    open_SML = "open",
    dead_SML = "dead",
    times_revived_SML = "times_revived",
    is_corrupted_SML = "is_corrupted",
    EPK_SML = "epk",


    -- 技能状态(Skill Buff)
    demon_form_tick_prevention_buff_SKBUF = "demon_form_tick_prevention_buff",
    on_rhoa_mount_SKBUF = "on_rhoa_mount",

    -- 地图数据名(Map data name)
    MapSinkhole_MDANA = "MapSinkhole",
    MapUniqueMegalith_MDANA = "MapUniqueMegalith",
    MapSandspit_MDANA = "MapSandspit",
    MapAugury_MDANA = "MapAugury",
    MapAugury_NoBoss_MDANA = "MapAugury_NoBoss",
    G_Endgame_Town_MDANA = "G_Endgame_Town",
    MapVaalFoundry_MDANA = "MapVaalFoundry",
    MapWetlands_MDANA = "MapWetlands",
    MapUniqueSelenite_MDANA = "MapUniqueSelenite",
    MapLeaguePortal_MDANA = "MapLeaguePortal",
    Abyss_Pinnacle_MDANA= "Abyss_Pinnacle",
    Abyss_Hub_MDANA = "Abyss_Hub",

    -- 地图玩法(Map play mod)
    Legendary_Map_MPMD = "傳奇地圖",

    -- 地图繁体中文名
    MapUniqueParadise_TWCH = "純淨樂園",
    MapUniqueSelenite_TWCH = "沉默洞穴",
    MapUniqueMegalith_TWCH = "艾茲麥巨石",
    MapUniqueLake_TWCH = "破裂迷湖",
    MapUniqueWildwood_TWCH = "翠綠荒林",

    -- 怪物名称(Monster name)
    snake_king = "巨蛇女王．瑪娜莎",
    The_Forgotten_Prisoner_NAME = "被遺忘的囚犯．帕拉薩",
    The_Tyrant_of_Bones_NAME = "骨之暴君．札瓦里",
    The_Terracotta_Warriors_NAME = "赤陶士兵",
    The_Stone_Soldiers_NAME = "石兵",
    The_vivid_jellyfish_NAME = "鮮明水母",
    Offering_sacrifices_to_fairies_NAME = "祭祀妖精",

    exp_add_valid_objects = {
        "甕", "壺", "屍體", "巢穴", "籃子", "小雕像", "石塊","鬆動碎石", "瓶子", "盒子", "腐爛木材", "保險箱", "腐爛木材","生鏽箱子"
    },

    
    PickUpSkillId = 0x2000C266

}

return game_str